/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ladder;

import ladder.domain.Ladder;
import ladder.view.LadderGameUI;

public class App {
    public static void main(String[] args) {
        int width = LadderGameUI.inputPeopleSize();
        int height = LadderGameUI.inputLadderHigh();
        Ladder ladder = new Ladder(height, width);
        LadderGameUI.outputLadder(ladder.toString());
    }
}
