/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kakaocorp.ladder.game;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class LadderGameTest {
    @Test
    void appHasAGreeting() {
        // 아직 테스트할 것이 없음.
        LadderGame ladderGame = new LadderGame();
        assertNotNull(ladderGame, "app should constructed.");
    }
}
